name: Publish

on: release

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
      - name: Build Asset
        run: |
          echo "test" > build.js
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.get_current_release.outputs.upload_url }}
          asset_path: ./build.js
          asset_name: build.js
          asset_content_type: text/javascript