name: Deloy To Dev

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Build
        run: |
          echo "built"
  deploy:
    name: Deploy to QA
    runs-on: ubuntu-latest
    needs: build
    environment: Dev
    
    steps:
      - name: Deploy
        run: |
          echo "deployed"