name: CI
on: push

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Tests passed'
            })